/**
 * "BitSub button": a bookmarklet that runs ON youtube.com (same origin, the person's own
 * connection), reads the caption list and opens BitSub with it. No server involved at all.
 * Plan B for when YouTube refuses to answer BitSub's relay.
 */
export function bookmarkletHref(appOrigin: string, messages: { open: string; fail: string }): string {
  // Tries the page's own WEB client first, then other clients, skipping caption URLs that need a token.
  const code = `(async()=>{const B=${JSON.stringify(appOrigin)};try{const u=new URL(location.href);let v=u.searchParams.get('v');if(!v){const m=u.pathname.match(/\\/(?:shorts|live|embed)\\/([\\w-]{11})/);v=m&&m[1]}if(!v||!/(^|\\.)youtube\\.com$/.test(location.hostname)){alert(${JSON.stringify(messages.open)});return}const g=(window.ytcfg&&ytcfg.get&&ytcfg.get('INNERTUBE_CLIENT_VERSION'))||'2.20260708.00.00';const C=[{clientName:'WEB',clientVersion:g},{clientName:'MWEB',clientVersion:'2.20260708.05.00'},{clientName:'IOS',clientVersion:'20.10.4',deviceMake:'Apple',deviceModel:'iPhone16,2',osName:'iPhone',osVersion:'18.3.2.22D82'},{clientName:'ANDROID',clientVersion:'20.10.38',androidSdkVersion:30}];let p=null,seen=0;for(const c of C){try{const r=await fetch('/youtubei/v1/player?prettyPrint=false',{method:'POST',credentials:'omit',headers:{'content-type':'application/json'},body:JSON.stringify({context:{client:Object.assign({hl:'en'},c)},videoId:v,playbackContext:{contentPlaybackContext:{signatureTimestamp:Math.floor(Date.now()/864e5)}},contentCheckOk:true,racyCheckOk:true})});const j=await r.json();const t=(j.captions&&j.captions.playerCaptionsTracklistRenderer)||{};const all=t.captionTracks||[];seen+=all.length;const k=all.filter(x=>!/[?&]exp=xpe/.test(x.baseUrl));const d=j.videoDetails||{};if(!p||k.length)p={v:v,t:d.title||'',a:d.author||'',l:+d.lengthSeconds||0,k:k.map(x=>[(()=>{const U=new URL(x.baseUrl,'https://www.youtube.com');U.hostname='www.youtube.com';return U.href})(),x.languageCode,x.kind==='asr'?1:0,x.isTranslatable===false?0:1]),x:(t.translationLanguages||[]).map(x=>x.languageCode)};if(k.length)break}catch(e){}}if(!p||(seen&&!p.k.length)){alert(${JSON.stringify(messages.fail)});return}window.open(B+'/watch?v='+v+'#yt='+encodeURIComponent(JSON.stringify(p)),'_blank')}catch(e){alert(${JSON.stringify(messages.fail)})}})();void 0`;
  return `javascript:${encodeURIComponent(code)}`;
}
