/**
 * Local history (IndexedDB via Dexie). Lives only in this browser.
 */
import Dexie, { type EntityTable } from 'dexie';
import type { Cue } from './transcript';
import type { ChatMessage, Provider } from './ai';

export interface SavedVideo {
  /** YouTube id, or "paste-<timestamp>" for pasted texts */
  id: string;
  videoId: string | null;
  title: string;
  author: string;
  lengthSeconds: number;
  language: string;
  autoGenerated: boolean;
  translated: boolean;
  pasted: boolean;
  cues: Cue[];
  /** language requested by the person (used to reopen the same view) */
  requested: string;
  openedAt: number;
}

export interface StoredMessage extends ChatMessage {
  preset?: string;
  provider?: Provider;
  model?: string;
  at: number;
  error?: string;
}

export interface SavedChat {
  /** `${videoKey}` (one conversation per video+language) */
  id: string;
  messages: StoredMessage[];
  updatedAt: number;
}

class BitSubDB extends Dexie {
  videos!: EntityTable<SavedVideo, 'id'>;
  chats!: EntityTable<SavedChat, 'id'>;

  constructor() {
    super('BitSubDB');
    this.version(1).stores({
      videos: 'id, videoId, openedAt',
      chats: 'id, updatedAt',
    });
  }
}

export const db = new BitSubDB();

export function videoKey(videoId: string, language: string): string {
  return `${videoId}:${language}`;
}

export async function saveVideo(v: SavedVideo) {
  try {
    await db.videos.put(v);
  } catch {
    /* private mode / quota: history is optional */
  }
}

export async function removeVideo(id: string) {
  await db.transaction('rw', db.videos, db.chats, async () => {
    await db.videos.delete(id);
    await db.chats.delete(id);
  });
}

export async function clearHistory() {
  await db.transaction('rw', db.videos, db.chats, async () => {
    await db.videos.clear();
    await db.chats.clear();
  });
}

export async function saveChat(id: string, messages: StoredMessage[]) {
  try {
    if (messages.length) await db.chats.put({ id, messages, updatedAt: Date.now() });
    else await db.chats.delete(id);
  } catch {
    /* ignore */
  }
}
