/**
 * Loads a video's transcript: history cache → caption list (visitor's browser) → caption text.
 */
import { useCallback, useEffect, useRef, useState } from 'react';
import {
  fetchCaptionCues,
  fetchVideoInfo,
  selectTrack,
  base,
  TranscriptError,
  type FetchErrorCode,
  type Selection,
  type VideoInfo,
} from '@/lib/youtube/client';
import { db, saveVideo, type SavedVideo } from '@/lib/db';
import { getSettings } from '@/lib/settings';
import type { Cue } from '@/lib/transcript';

export type Phase = 'finding' | 'grabbing' | 'translating';
export type Notice = 'translateFailed' | 'notInLanguage' | null;

export interface LoadedVideo {
  id: string;
  videoId: string | null;
  title: string;
  author: string;
  lengthSeconds: number;
  language: string;
  autoGenerated: boolean;
  translated: boolean;
  pasted: boolean;
  cues: Cue[];
  requested: string;
}

export type VideoState =
  | { status: 'loading'; phase: Phase; videoId: string; title?: string }
  | { status: 'ready'; video: LoadedVideo; notice: Notice; info: VideoInfo | null }
  | { status: 'error'; error: FetchErrorCode | 'playlist'; videoId: string; title?: string };

/** Signed caption URLs expire after a few hours; don't reuse a list older than this. */
const INFO_MAX_AGE = 45 * 60 * 1000;

function toLoaded(videoId: string, info: VideoInfo, sel: Selection, cues: Cue[], requested: string): LoadedVideo {
  return {
    id: videoId,
    videoId,
    title: info.title,
    author: info.author,
    lengthSeconds: info.lengthSeconds || Math.ceil(cues[cues.length - 1]?.end ?? 0),
    language: sel.language,
    autoGenerated: sel.autoGenerated,
    translated: sel.translated,
    pasted: false,
    cues,
    requested,
  };
}

async function persist(v: LoadedVideo) {
  if (!getSettings().saveHistory) return;
  const saved: SavedVideo = { ...v, openedAt: Date.now() };
  await saveVideo(saved);
}

export function useVideo(videoId: string | null, requested: string) {
  const [state, setState] = useState<VideoState | null>(null);
  const [attempt, setAttempt] = useState(0);
  const infoRef = useRef<{ id: string; info: VideoInfo; at: number } | null>(null);

  const retry = useCallback(() => setAttempt((n) => n + 1), []);

  useEffect(() => {
    if (!videoId) return;
    const ctrl = new AbortController();
    let cancelled = false;
    const set = (s: VideoState) => {
      if (!cancelled) setState(s);
    };

    // Show "loading" right away instead of the previous video while IndexedDB answers.
    setState((s) =>
      s && (s.status === 'loading' ? s.videoId : s.status === 'error' ? s.videoId : s.video.videoId) === videoId ? s : null
    );

    void (async () => {
      // 1. History (instant, works offline)
      const saved = await db.videos.get(videoId).catch(() => undefined);
      if (saved && saved.cues.length && saved.requested === requested && attempt === 0) {
        set({ status: 'ready', video: saved, notice: null, info: null });
        if (getSettings().saveHistory) void db.videos.update(videoId, { openedAt: Date.now() }).catch(() => undefined);
        return;
      }

      set({ status: 'loading', phase: 'finding', videoId, title: saved?.title });
      try {
        // 2. Caption list (memory, or asked by the browser)
        let info: VideoInfo;
        const cachedInfo = infoRef.current;
        const fresh = cachedInfo?.id === videoId && attempt === 0 && Date.now() - cachedInfo.at < INFO_MAX_AGE;
        if (fresh && cachedInfo) info = cachedInfo.info;
        else info = await fetchVideoInfo(videoId, ctrl.signal);
        infoRef.current = { id: videoId, info, at: fresh && cachedInfo ? cachedInfo.at : Date.now() };

        const sel = selectTrack(info, requested);
        if (!sel) throw new TranscriptError('no_captions');

        // 3. Caption text, straight from YouTube
        set({ status: 'loading', phase: sel.translated ? 'translating' : 'grabbing', videoId, title: info.title });
        let notice: Notice = null;
        let finalSel = sel;
        let cues: Cue[];
        try {
          cues = await fetchCaptionCues(sel, ctrl.signal);
        } catch (e) {
          if (!sel.translated || ctrl.signal.aborted) throw e;
          // Translation refused: show the original language instead
          const original = selectTrack(info, 'original');
          if (!original) throw e;
          finalSel = original;
          cues = await fetchCaptionCues(original, ctrl.signal);
          notice = 'translateFailed';
        }
        if (!notice && requested !== 'original' && !finalSel.translated && base(finalSel.language) !== base(requested)) {
          notice = 'notInLanguage';
        }
        const video = toLoaded(videoId, info, finalSel, cues, requested);
        set({ status: 'ready', video, notice, info });
        void persist(video);
      } catch (e) {
        if (ctrl.signal.aborted) return;
        // Offline but we have an older copy in another language: better than nothing
        if (
          saved?.cues.length &&
          e instanceof TranscriptError &&
          (e.code === 'offline' || e.code === 'blocked' || e.code === 'rate_limited')
        ) {
          set({ status: 'ready', video: saved, notice: null, info: null });
          return;
        }
        const code = e instanceof TranscriptError ? e.code : 'unknown';
        const relayTitle =
          e instanceof TranscriptError && code === 'no_captions' && !/^(no_captions|empty track)$/.test(e.message)
            ? e.message
            : undefined;
        set({ status: 'error', error: code, videoId, title: relayTitle ?? saved?.title });
      }
    })();

    return () => {
      cancelled = true;
      ctrl.abort();
    };
  }, [videoId, requested, attempt]);

  return { state, retry };
}
