/**
 * Loads a video's transcript: history cache → relay (or bookmarklet import) → YouTube captions.
 */
import { useCallback, useEffect, useRef, useState } from 'react';
import {
  fetchCaptionCues,
  fetchVideoInfo,
  selectTrack,
  base,
  TranscriptError,
  type FetchErrorCode,
  type Selection,
  type VideoInfo,
} from '@/lib/youtube/client';
import { db, saveVideo, type SavedVideo } from '@/lib/db';
import { getSettings } from '@/lib/settings';
import type { Cue } from '@/lib/transcript';

export type Phase = 'finding' | 'grabbing' | 'translating';
export type Notice = 'translateFailed' | 'notInLanguage' | null;

export interface LoadedVideo {
  id: string;
  videoId: string | null;
  title: string;
  author: string;
  lengthSeconds: number;
  language: string;
  autoGenerated: boolean;
  translated: boolean;
  pasted: boolean;
  cues: Cue[];
  requested: string;
}

export type VideoState =
  | { status: 'loading'; phase: Phase; videoId: string; title?: string }
  | { status: 'ready'; video: LoadedVideo; notice: Notice; info: VideoInfo | null }
  | { status: 'error'; error: FetchErrorCode | 'playlist'; videoId: string; title?: string };

/** Payload handed over by the "BitSub button" bookmarklet (runs on youtube.com). */
interface ImportPayload {
  v: string;
  t?: string;
  a?: string;
  l?: number;
  k?: [string, string, number, number][];
  x?: string[];
}

const str = (v: unknown, max = 300): string => (typeof v === 'string' ? v.slice(0, max) : '');
const LANG_RE = /^[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$/;

/** Only real YouTube caption URLs are accepted from the hand-off (never another host). */
function safeCaptionUrl(raw: unknown): string | null {
  if (typeof raw !== 'string') return null;
  try {
    const u = new URL(raw, 'https://www.youtube.com');
    if (u.protocol !== 'https:' || u.hostname !== 'www.youtube.com' || u.pathname !== '/api/timedtext') return null;
    if (/[?&]exp=xpe/.test(u.search)) return null; // needs a token we don't have
    u.searchParams.delete('fmt');
    return u.toString();
  } catch {
    return null;
  }
}

// Parsed once per video, so later re-renders (or dev StrictMode) still see it after the URL is cleaned.
const imported = new Map<string, VideoInfo>();

export function readImportHash(videoId: string): VideoInfo | null {
  const m = /[#&]yt=([^&]+)/.exec(window.location.hash);
  if (!m?.[1]) return imported.get(videoId) ?? null;
  try {
    const p = JSON.parse(decodeURIComponent(m[1])) as ImportPayload;
    if (!p || p.v !== videoId || !Array.isArray(p.k)) return null;
    const tracks: VideoInfo['tracks'] = [];
    for (const k of p.k.slice(0, 100)) {
      if (!Array.isArray(k)) continue;
      const url = safeCaptionUrl(k[0]);
      const lang = str(k[1], 20);
      if (!url || !LANG_RE.test(lang)) continue;
      tracks.push({ baseUrl: url, languageCode: lang, name: lang, kind: k[2] ? 'asr' : 'manual', isTranslatable: k[3] !== 0 });
    }
    const info: VideoInfo = {
      videoId,
      title: str(p.t),
      author: str(p.a, 120),
      lengthSeconds: typeof p.l === 'number' && Number.isFinite(p.l) ? Math.max(0, p.l) : 0,
      isLive: false,
      tracks,
      translationLanguages: Array.isArray(p.x) ? p.x.filter((x): x is string => typeof x === 'string' && LANG_RE.test(x)) : [],
    };
    if (tracks.length) imported.set(videoId, info);
    return info;
  } catch {
    return null;
  }
}

/** Signed caption URLs expire after a few hours; don't reuse a list older than this. */
const INFO_MAX_AGE = 45 * 60 * 1000;

function toLoaded(videoId: string, info: VideoInfo, sel: Selection, cues: Cue[], requested: string): LoadedVideo {
  return {
    id: videoId,
    videoId,
    title: info.title,
    author: info.author,
    lengthSeconds: info.lengthSeconds || Math.ceil(cues[cues.length - 1]?.end ?? 0),
    language: sel.language,
    autoGenerated: sel.autoGenerated,
    translated: sel.translated,
    pasted: false,
    cues,
    requested,
  };
}

async function persist(v: LoadedVideo) {
  if (!getSettings().saveHistory) return;
  const saved: SavedVideo = { ...v, openedAt: Date.now() };
  await saveVideo(saved);
}

export function useVideo(videoId: string | null, requested: string) {
  const [state, setState] = useState<VideoState | null>(null);
  const [attempt, setAttempt] = useState(0);
  const infoRef = useRef<{ id: string; info: VideoInfo; at: number } | null>(null);

  const retry = useCallback(() => setAttempt((n) => n + 1), []);

  useEffect(() => {
    if (!videoId) return;
    const ctrl = new AbortController();
    let cancelled = false;
    const set = (s: VideoState) => {
      if (!cancelled) setState(s);
    };

    // Read the bookmarklet hand-off now, before anything rewrites the URL.
    const hashInfo = readImportHash(videoId);
    // Show "loading" right away instead of the previous video while IndexedDB answers.
    setState((s) =>
      s && (s.status === 'loading' ? s.videoId : s.status === 'error' ? s.videoId : s.video.videoId) === videoId ? s : null
    );

    void (async () => {
      // 1. History (instant, works offline)
      const saved = await db.videos.get(videoId).catch(() => undefined);
      if (saved && saved.cues.length && saved.requested === requested && !hashInfo && attempt === 0) {
        set({ status: 'ready', video: saved, notice: null, info: null });
        if (getSettings().saveHistory) void db.videos.update(videoId, { openedAt: Date.now() }).catch(() => undefined);
        return;
      }

      set({ status: 'loading', phase: 'finding', videoId, title: saved?.title });
      try {
        // 2. Caption list (bookmarklet hand-off, memory, or relay)
        let info: VideoInfo;
        const cachedInfo = infoRef.current;
        const fresh = cachedInfo?.id === videoId && attempt === 0 && Date.now() - cachedInfo.at < INFO_MAX_AGE;
        if (hashInfo?.tracks.length) info = hashInfo;
        else if (fresh && cachedInfo) info = cachedInfo.info;
        else info = await fetchVideoInfo(videoId, ctrl.signal);
        infoRef.current = { id: videoId, info, at: fresh && cachedInfo ? cachedInfo.at : Date.now() };
        if (hashInfo) window.history.replaceState(null, '', window.location.pathname + window.location.search);

        const sel = selectTrack(info, requested);
        if (!sel) throw new TranscriptError('no_captions');

        // 3. Caption text, straight from YouTube
        set({ status: 'loading', phase: sel.translated ? 'translating' : 'grabbing', videoId, title: info.title });
        let notice: Notice = null;
        let finalSel = sel;
        let cues: Cue[];
        try {
          cues = await fetchCaptionCues(sel, ctrl.signal);
        } catch (e) {
          if (!sel.translated || ctrl.signal.aborted) throw e;
          // Translation refused: show the original language instead
          const original = selectTrack(info, 'original');
          if (!original) throw e;
          finalSel = original;
          cues = await fetchCaptionCues(original, ctrl.signal);
          notice = 'translateFailed';
        }
        if (!notice && requested !== 'original' && !finalSel.translated && base(finalSel.language) !== base(requested)) {
          notice = 'notInLanguage';
        }
        const video = toLoaded(videoId, info, finalSel, cues, requested);
        set({ status: 'ready', video, notice, info });
        void persist(video);
      } catch (e) {
        if (ctrl.signal.aborted) return;
        // Offline but we have an older copy in another language: better than nothing
        if (
          saved?.cues.length &&
          e instanceof TranscriptError &&
          (e.code === 'offline' || e.code === 'blocked' || e.code === 'rate_limited')
        ) {
          set({ status: 'ready', video: saved, notice: null, info: null });
          return;
        }
        const code = e instanceof TranscriptError ? e.code : 'unknown';
        const relayTitle =
          e instanceof TranscriptError && code === 'no_captions' && !/^(no_captions|empty track)$/.test(e.message)
            ? e.message
            : undefined;
        set({ status: 'error', error: code, videoId, title: relayTitle ?? saved?.title });
      }
    })();

    return () => {
      cancelled = true;
      ctrl.abort();
    };
  }, [videoId, requested, attempt]);

  return { state, retry };
}
