/**
 * Browser side of the transcript flow.
 *
 * 1. Ask our tiny relay (/api/tracks) for the video's caption list. The relay only sees
 *    the video id; YouTube blocks this step for any site that isn't youtube.com.
 * 2. Download the caption text straight from YouTube (its caption server allows any site),
 *    so the text itself never passes through BitSub.
 */
import { normalizeCues, type Cue } from '../transcript';
import { fetchVideoInfoInBrowser } from './browser-player';

export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  name: string;
  kind: 'asr' | 'manual';
  isTranslatable: boolean;
}

export interface VideoInfo {
  videoId: string;
  title: string;
  author: string;
  lengthSeconds: number;
  isLive: boolean;
  tracks: CaptionTrack[];
  translationLanguages: string[];
}

export type FetchErrorCode =
  | 'invalid_link'
  | 'not_found'
  | 'unavailable'
  | 'private'
  | 'age_restricted'
  | 'live'
  | 'no_captions'
  | 'rate_limited'
  | 'blocked'
  | 'offline'
  | 'unknown';

export class TranscriptError extends Error {
  code: FetchErrorCode;
  constructor(code: FetchErrorCode, message?: string) {
    super(message ?? code);
    this.name = 'TranscriptError';
    this.code = code;
  }
}

export interface Selection {
  track: CaptionTrack;
  /** When set, YouTube translates the track into this language */
  translateTo?: string;
  /** Final language of the text we got */
  language: string;
  autoGenerated: boolean;
  translated: boolean;
}

export const base = (code: string) => code.toLowerCase().split(/[-_]/)[0] ?? code.toLowerCase();

/** Language actually spoken in the video (YouTube's auto captions follow the audio). */
export function spokenLanguage(tracks: CaptionTrack[]): string | undefined {
  return tracks.find((t) => t.kind === 'asr')?.languageCode ?? tracks.find((t) => t.kind === 'manual')?.languageCode;
}

/**
 * Pick the best track for the language the person wants.
 * `wanted` = a language code (pt-BR, en, esâ€¦) or "original".
 * Order: made by the channel â†’ auto captions â†’ YouTube auto-translation.
 */
export function selectTrack(info: VideoInfo, wanted: string): Selection | null {
  const tracks = info.tracks;
  if (!tracks.length) return null;
  const spoken = spokenLanguage(tracks);
  const pick = (t: CaptionTrack): Selection => ({
    track: t,
    language: t.languageCode,
    autoGenerated: t.kind === 'asr',
    translated: false,
  });

  if (wanted === 'original') {
    const manualSpoken = spoken ? tracks.find((t) => t.kind === 'manual' && base(t.languageCode) === base(spoken)) : undefined;
    const asr = tracks.find((t) => t.kind === 'asr');
    const firstManual = tracks.find((t) => t.kind === 'manual');
    const t = manualSpoken ?? asr ?? firstManual ?? tracks[0]!;
    return pick(t);
  }

  const wb = base(wanted);
  const exactManual = tracks.find((t) => t.kind === 'manual' && t.languageCode.toLowerCase() === wanted.toLowerCase());
  const baseManual = tracks.find((t) => t.kind === 'manual' && base(t.languageCode) === wb);
  const baseAsr = tracks.find((t) => t.kind === 'asr' && base(t.languageCode) === wb);
  const direct = exactManual ?? baseManual ?? baseAsr;
  if (direct) return pick(direct);

  // Translate: prefer a human track in the spoken language, then any human track, then auto.
  const translatable = tracks.filter((t) => t.isTranslatable);
  const source =
    translatable.find((t) => t.kind === 'manual' && spoken && base(t.languageCode) === base(spoken)) ??
    translatable.find((t) => t.kind === 'manual') ??
    translatable.find((t) => t.kind === 'asr');
  if (!source) {
    // Can't translate: fall back to what exists (original language)
    const fallback = tracks.find((t) => t.kind === 'manual') ?? tracks[0]!;
    return pick(fallback);
  }
  const target =
    info.translationLanguages.find((l) => l.toLowerCase() === wanted.toLowerCase()) ??
    info.translationLanguages.find((l) => base(l) === wb) ??
    wb;
  return {
    track: source,
    translateTo: target,
    language: target,
    autoGenerated: source.kind === 'asr',
    translated: true,
  };
}

// ---------------------------------------------------------------- relay

const TIMEOUT_MS = 20000;

async function withTimeout<T>(p: (signal: AbortSignal) => Promise<T>, signal?: AbortSignal): Promise<T> {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), TIMEOUT_MS);
  const onAbort = () => ctrl.abort();
  signal?.addEventListener('abort', onAbort);
  try {
    return await p(ctrl.signal);
  } finally {
    clearTimeout(timer);
    signal?.removeEventListener('abort', onAbort);
  }
}

/**
 * Caption list for a video: first from the visitor's own browser (no server, their IP),
 * then from our relay if the browser path can't answer.
 */
export async function fetchVideoInfo(videoId: string, signal?: AbortSignal): Promise<VideoInfo> {
  if (!navigator.onLine) throw new TranscriptError('offline');
  try {
    const result = await fetchVideoInfoInBrowser(videoId, signal);
    if (result.ok) return result.info;
    throw new TranscriptError(result.code);
  } catch (e) {
    if (e instanceof TranscriptError || signal?.aborted) throw e;
    // Browser path unavailable (YouTube changed something, flagged network…): use the relay.
  }
  return fetchVideoInfoFromRelay(videoId, signal);
}

async function fetchVideoInfoFromRelay(videoId: string, signal?: AbortSignal): Promise<VideoInfo> {
  let res: Response;
  try {
    res = await withTimeout(
      (s) => fetch(`/api/tracks?v=${encodeURIComponent(videoId)}`, { headers: { 'x-bitsub': '1' }, signal: s }),
      signal
    );
  } catch (e) {
    if (signal?.aborted) throw e;
    throw new TranscriptError(navigator.onLine ? 'unknown' : 'offline', e instanceof Error ? e.message : undefined);
  }
  const data = (await res.json().catch(() => null)) as (VideoInfo & { error?: FetchErrorCode; message?: string }) | null;
  if (!res.ok || !data || data.error) {
    throw new TranscriptError(data?.error ?? (res.status === 429 ? 'rate_limited' : 'unknown'), data?.message);
  }
  return data;
}

// ---------------------------------------------------------------- caption text

interface Json3 {
  events?: {
    tStartMs?: number;
    dDurationMs?: number;
    aAppend?: number;
    segs?: { utf8?: string; tOffsetMs?: number }[];
  }[];
}

export function parseJson3(json: Json3): Cue[] {
  const cues: Cue[] = [];
  for (const ev of json.events ?? []) {
    if (!ev.segs || ev.aAppend) continue;
    const text = ev.segs.map((s) => s.utf8 ?? '').join('');
    if (!text.trim()) continue;
    const start = (ev.tStartMs ?? 0) / 1000;
    const end = start + (ev.dDurationMs ?? 0) / 1000;
    cues.push({ start, end, text });
  }
  return normalizeCues(cues);
}

/** Minimal parser for the XML formats, used if json3 ever stops working. */
export function parseTimedTextXml(xml: string): Cue[] {
  const doc = new DOMParser().parseFromString(xml, 'text/xml');
  const cues: Cue[] = [];
  // srv3: <p t="ms" d="ms">â€¦<s>word</s>â€¦</p>
  doc.querySelectorAll('p').forEach((p) => {
    const t = Number(p.getAttribute('t') ?? 0) / 1000;
    const d = Number(p.getAttribute('d') ?? 0) / 1000;
    const text = p.textContent ?? '';
    if (text.trim()) cues.push({ start: t, end: t + d, text });
  });
  // legacy: <text start="s" dur="s">â€¦</text>
  doc.querySelectorAll('text').forEach((n) => {
    const t = Number(n.getAttribute('start') ?? 0);
    const d = Number(n.getAttribute('dur') ?? 0);
    const text = n.textContent ?? '';
    if (text.trim()) cues.push({ start: t, end: t + d, text });
  });
  return normalizeCues(cues);
}

export function captionUrl(sel: Selection, fmt: 'json3' | 'srv3' = 'json3'): string {
  const url = new URL(sel.track.baseUrl);
  url.searchParams.set('fmt', fmt);
  if (sel.translateTo) url.searchParams.set('tlang', sel.translateTo);
  else url.searchParams.delete('tlang');
  return url.toString();
}

export async function fetchCaptionCues(sel: Selection, signal?: AbortSignal): Promise<Cue[]> {
  const load = async (fmt: 'json3' | 'srv3') => {
    const res = await withTimeout((s) => fetch(captionUrl(sel, fmt), { signal: s, credentials: 'omit' }), signal);
    const text = await res.text();
    if (res.status === 429 || /<title>Sorry/i.test(text)) throw new TranscriptError('rate_limited');
    if (!res.ok) throw new TranscriptError('unknown', `HTTP ${res.status}`);
    return text;
  };
  let raw: string;
  try {
    raw = await load('json3');
  } catch (e) {
    if (e instanceof TranscriptError) throw e;
    if (signal?.aborted) throw e;
    // YouTube's "too many requests" answer has no CORS header, so the browser only
    // reports a network error. Online + network error here = YouTube asked for a pause.
    throw new TranscriptError(navigator.onLine ? 'rate_limited' : 'offline');
  }
  let cues: Cue[] = [];
  if (raw.trim().startsWith('{')) {
    try {
      cues = parseJson3(JSON.parse(raw) as Json3);
    } catch {
      cues = [];
    }
  }
  if (!cues.length) {
    const xml = await load('srv3').catch(() => '');
    if (xml.trim().startsWith('<')) cues = parseTimedTextXml(xml);
  }
  if (!cues.length) throw new TranscriptError('no_captions', 'empty track');
  return cues;
}
