import { useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useVideo, type LoadedVideo, type Notice, type Phase } from '@/hooks/useVideo';
import { useCaptionLang, setSessionCaptionLang } from '@/hooks/useCaptionLang';
import { navigate, watchPath } from '@/lib/router';
import { watchUrl } from '@/lib/youtube/url';
import { exportTranscript } from '@/lib/transcript';
import { copyText, downloadFile } from '@/lib/files';
import { toast } from '@/lib/toast';
import { useKeys, useSettings } from '@/lib/settings';
import { Footer, Page } from '@/components/Shell';
import { UrlForm } from '@/components/UrlForm';
import { VideoHeader } from '@/components/VideoHeader';
import { TranscriptPanel } from '@/components/TranscriptPanel';
import { DownloadPanel, useExport } from '@/components/DownloadPanel';
import { AiPanel, requestPreset } from '@/components/AiPanel';
import { ErrorView } from '@/components/ErrorView';
import { Icon } from '@/components/Icon';
import { ThinkingMascot } from '@/components/ThinkingMascot';
import { Dots, cn } from '@/components/ui';

function Loading({ phase, videoId, title }: { phase: Phase; videoId: string; title?: string }) {
  const { t } = useTranslation();
  const order: Phase[] = ['finding', phase === 'translating' ? 'translating' : 'grabbing'];
  const current = order.indexOf(phase);
  return (
    <section className="grid gap-6 md:grid-cols-12 md:gap-8" aria-busy="true">
      <div className="md:col-span-5">
        <div className="card relative flex aspect-video items-center justify-center overflow-hidden bg-[#203c56]">
          <img
            src={`https://i.ytimg.com/vi/${videoId}/mqdefault.jpg`}
            alt=""
            className="absolute inset-0 h-full w-full object-cover opacity-30"
          />
          <ThinkingMascot size={176} className="relative" />
        </div>
      </div>
      <div className="flex flex-col justify-center gap-5 md:col-span-7">
        {title ? (
          <p className="text-balance text-2xl font-semibold leading-tight">{title}</p>
        ) : (
          <div className="h-8 w-3/4 animate-pulse bg-surface-alt" />
        )}
        <ol className="space-y-3" aria-live="polite">
          {order.map((p, i) => (
            <li key={p} className={cn('flex items-center gap-3 text-lg', i > current && 'text-faint')}>
              <span
                className={cn(
                  'flex h-8 w-8 items-center justify-center border-2 border-line',
                  i < current ? 'bg-ink text-on-ink' : i === current ? 'bg-primary text-on-primary' : 'bg-surface'
                )}
              >
                {i < current ? (
                  <Icon name="check" size={16} strokeWidth={3} />
                ) : i === current ? (
                  <Dots size="sm" />
                ) : (
                  <span className="pixel text-[9px]">{i + 1}</span>
                )}
              </span>
              <span className={cn(i === current && 'font-semibold')}>{t(`status.${p}`)}</span>
            </li>
          ))}
        </ol>
      </div>
    </section>
  );
}

export function Result({
  video,
  notice,
  requested,
  onLanguage,
  start,
}: {
  video: LoadedVideo;
  notice: Notice;
  requested: string;
  onLanguage?: (lang: string) => void;
  start?: number;
}) {
  const { t } = useTranslation();
  const [tab, setTab] = useState<'text' | 'ai'>('text');
  const keys = useKeys();
  const settings = useSettings();
  const url = video.videoId ? watchUrl(video.videoId) : undefined;
  const { build, format } = useExport(video.cues, video.title, video.language, url);
  const pendingPreset = useRef(false);

  useEffect(() => {
    if (tab === 'ai' && pendingPreset.current) {
      pendingPreset.current = false;
      setTimeout(() => requestPreset('summary'), 50);
    }
  }, [tab]);

  const summarize = () => {
    const hasKey = Boolean(keys[settings.provider]);
    if (window.matchMedia('(min-width: 1024px)').matches) {
      document.getElementById('ai-title')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
      if (hasKey) requestPreset('summary');
      return;
    }
    if (hasKey) pendingPreset.current = true;
    setTab('ai');
    window.scrollTo({ top: document.getElementById('result-tabs')?.offsetTop ?? 0, behavior: 'smooth' });
  };

  const aiVideo = {
    id: video.id,
    title: video.title,
    author: video.author,
    url: url ?? '',
    language: video.language,
    autoGenerated: video.autoGenerated,
    cues: video.cues,
  };

  return (
    <>
      <VideoHeader video={video} notice={notice} requested={requested} onLanguage={onLanguage} start={start} />

      <div
        id="result-tabs"
        role="tablist"
        aria-label={t('tabs.text')}
        className="sticky top-[var(--header-h)] z-20 mt-8 flex border-2 border-line bg-surface lg:hidden"
      >
        {(['text', 'ai'] as const).map((k) => (
          <button
            key={k}
            role="tab"
            type="button"
            aria-selected={tab === k}
            onClick={() => setTab(k)}
            className={cn(
              'flex flex-1 items-center justify-center gap-2 py-3 font-semibold transition-colors',
              tab === k ? 'bg-primary text-on-primary' : 'hover:bg-surface-alt'
            )}
          >
            <Icon name={k === 'text' ? 'text' : 'sparkle'} size={18} />
            {t(k === 'text' ? 'tabs.text' : 'tabs.ai')}
          </button>
        ))}
      </div>

      <div className="mt-6 grid gap-8 lg:mt-10 lg:grid-cols-12">
        <div className={cn('space-y-10 lg:col-span-7 lg:block', tab === 'text' ? 'block' : 'hidden')}>
          <DownloadPanel cues={video.cues} title={video.title} language={video.language} url={url} />
          <TranscriptPanel cues={video.cues} title={video.title} url={url} />
        </div>
        <div className={cn('lg:col-span-5 lg:block', tab === 'ai' ? 'block' : 'hidden')}>
          <div className="lg:sticky lg:top-24 lg:flex lg:max-h-[calc(100dvh-7.5rem)] lg:flex-col">
            <AiPanel video={aiVideo} />
          </div>
        </div>
      </div>

      {/* Thumb-zone action bar (phones) */}
      <div className="fixed inset-x-0 bottom-0 z-30 border-t-2 border-line bg-bg/95 px-3 pt-2.5 backdrop-blur-sm safe-bottom lg:hidden">
        <div className="mx-auto flex max-w-xl gap-2 pb-2.5">
          <button
            type="button"
            className="btn btn-sm flex-1"
            onClick={() => {
              const f = build(format);
              downloadFile(f.name, f.content, f.mime);
              toast(t('download.done'), 'success');
            }}
          >
            <Icon name="download" size={16} />
            {t('common.download')}
          </button>
          <button
            type="button"
            className="btn btn-sm flex-1"
            onClick={() =>
              void copyText(exportTranscript(video.cues, settings.showTime ? 'txt-time' : 'txt')).then((ok) =>
                toast(ok ? t('toast.copied') : t('toast.copyFailed'), ok ? 'success' : 'error')
              )
            }
          >
            <Icon name="copy" size={16} />
            {t('common.copy')}
          </button>
          <button type="button" className="btn btn-sm btn-primary flex-[1.3]" onClick={summarize}>
            <Icon name="sparkle" size={16} />
            {t('ai.presets.summary')}
          </button>
        </div>
      </div>
    </>
  );
}

export function Watch({ videoId, langParam, start }: { videoId: string; langParam: string | null; start?: number }) {
  const [preferred] = useCaptionLang();
  const requested = langParam || preferred;
  const { state, retry } = useVideo(videoId, requested);

  useEffect(() => {
    if (!langParam) navigate(watchPath(videoId, requested, start), { replace: true, scroll: false });
  }, [langParam, videoId, requested, start]);

  const onLanguage = (lang: string) => {
    setSessionCaptionLang(lang);
    navigate(watchPath(videoId, lang), { replace: true, scroll: false });
  };

  const focusInput = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
    setTimeout(() => (document.querySelector('main input[type="url"]') as HTMLInputElement | null)?.focus(), 250);
  };

  return (
    <>
      <Page className="pb-28 pt-6 lg:pb-10">
        <div className="mb-8 border-b-2 border-line pb-6">
          <UrlForm compact lang={requested} onLangChange={onLanguage} />
        </div>
        {!state || state.status === 'loading' ? (
          <Loading
            phase={state?.status === 'loading' ? state.phase : 'finding'}
            videoId={videoId}
            title={state?.status === 'loading' ? state.title : undefined}
          />
        ) : state.status === 'error' ? (
          <ErrorView error={state.error} videoId={videoId} title={state.title} onRetry={retry} onAnother={focusInput} />
        ) : (
          <Result video={state.video} notice={state.notice} requested={requested} onLanguage={onLanguage} start={start} />
        )}
      </Page>
      <Footer />
    </>
  );
}
