import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { useTranslation } from 'react-i18next';
import { AiError, estimateTokens, pickModel, streamChat, validateKey, type ChatMessage, type Provider } from '@/lib/ai';
import { PRESETS, PRESET_PROMPTS, buildSystemPrompt, chunkText, type PresetId } from '@/lib/prompts';
import { db, saveChat, type StoredMessage } from '@/lib/db';
import { getSettings, setKey, updateSettings, useKeys, useSettings } from '@/lib/settings';
import { knownModels, rememberModels } from '@/lib/models';
import { transcriptForAI, type Cue } from '@/lib/transcript';
import { copyText, downloadFile } from '@/lib/files';
import { toast } from '@/lib/toast';
import { Link } from '@/lib/router';
import { currentLanguage } from '@/i18n';
import { languageLabel } from '@/lib/languages';
import { Icon } from './Icon';
import { KeySetup } from './KeySetup';
import { ThinkingMascot } from './ThinkingMascot';
import { Markdown } from './Markdown';
import { Mascot } from './Mascot';
import { Button, Callout, cn } from './ui';
import { aiErrorMessage } from './aiErrors';

// Lets other parts of the page (e.g. the mobile action bar) ask for a preset.
const PRESET_EVENT = 'bitsub:preset';
export function requestPreset(id: PresetId) {
  window.dispatchEvent(new CustomEvent(PRESET_EVENT, { detail: id }));
}

export interface AiVideo {
  id: string;
  title: string;
  author: string;
  url: string;
  language: string;
  autoGenerated: boolean;
  cues: Cue[];
}

/** Hard cap before we switch to "summarize by parts" (≈ tokens). */
const MAX_CONTEXT_TOKENS = 600_000;
const reducedCache = new Map<string, string>();

export function AiPanel({ video }: { video: AiVideo }) {
  const { t } = useTranslation();
  const settings = useSettings();
  const keys = useKeys();
  const provider = settings.provider;
  const apiKey = keys[provider];

  return (
    <section aria-labelledby="ai-title" className="card flex min-h-0 flex-col">
      <div className="flex items-center justify-between gap-3 border-b-2 border-line bg-ink px-4 py-3 text-on-ink sm:px-5">
        <h2 id="ai-title" className="flex items-center gap-2.5 text-lg font-semibold">
          <Icon name="sparkle" size={20} />
          {t('ai.title')}
        </h2>
        {apiKey ? <ProviderSwitch provider={provider} /> : null}
      </div>
      <div className="flex min-h-0 flex-1 flex-col p-4 sm:p-5">
        {apiKey ? <Chat key={`${video.id}:${provider}`} video={video} provider={provider} apiKey={apiKey} /> : <KeySetup />}
      </div>
    </section>
  );
}

function ProviderSwitch({ provider }: { provider: Provider }) {
  const keys = useKeys();
  const other: Provider = provider === 'gemini' ? 'openai' : 'gemini';
  return (
    <div className="flex items-center gap-1 text-sm">
      {(['gemini', 'openai'] as const).map((p) => (
        <button
          key={p}
          type="button"
          onClick={() => updateSettings({ provider: p })}
          aria-pressed={p === provider}
          className={cn(
            'border-2 px-2 py-0.5 font-semibold transition-colors',
            p === provider ? 'border-on-ink bg-on-ink text-ink' : 'border-transparent opacity-75 hover:opacity-100'
          )}
          title={p === other && !keys[other] ? '+' : undefined}
        >
          {p === 'gemini' ? 'Gemini' : 'ChatGPT'}
        </button>
      ))}
    </div>
  );
}

async function withModelFallback(
  provider: Provider,
  apiKey: string,
  model: string,
  run: (m: string) => Promise<string>
): Promise<string> {
  try {
    return await run(model);
  } catch (e) {
    // Only when the chosen model no longer exists: switch to the best available one.
    if (!(e instanceof AiError && e.code === 'model_not_found')) throw e;
    const check = await validateKey(provider, apiKey);
    if (!check.ok) throw e;
    rememberModels(provider, check.models);
    const next = pickModel(
      provider,
      check.models.filter((m) => m !== model)
    );
    if (!next || next === model) throw e;
    updateSettings({ models: { ...getSettings().models, [provider]: next } });
    return run(next);
  }
}

function Chat({ video, provider, apiKey }: { video: AiVideo; provider: Provider; apiKey: string }) {
  const { t } = useTranslation();
  const settings = useSettings();
  const ui = currentLanguage();
  const answerLang = settings.answerLang === 'app' ? ui : settings.answerLang;
  const model = settings.models[provider] ?? pickModel(provider, knownModels(provider));
  const [messages, setMessages] = useState<StoredMessage[]>([]);
  const [draft, setDraft] = useState('');
  const [streaming, setStreaming] = useState<string | null>(null);
  const [progress, setProgress] = useState<string | null>(null);
  const [error, setError] = useState<{ text: string; retry: StoredMessage[] } | null>(null);
  const abort = useRef<AbortController | null>(null);
  const scroller = useRef<HTMLDivElement>(null);
  const touched = useRef(false);
  const busy = streaming !== null;
  const waitingFirstWord = busy && !streaming;
  const [slow, setSlow] = useState(false);

  // No first word after a while: tell the person instead of leaving them guessing.
  useEffect(() => {
    setSlow(false);
    if (!waitingFirstWord) return;
    const timer = setTimeout(() => setSlow(true), 12000);
    return () => clearTimeout(timer);
  }, [waitingFirstWord]);

  // Load the saved conversation for this video
  useEffect(() => {
    let alive = true;
    void db.chats
      .get(video.id)
      .then((c) => {
        // Don't overwrite a conversation the person already started meanwhile.
        if (alive && c && !touched.current) setMessages(c.messages);
      })
      .catch(() => undefined);
    return () => {
      alive = false;
      abort.current?.abort();
    };
  }, [video.id]);

  useEffect(() => {
    // Scroll only the chat box, never the page.
    const el = scroller.current;
    if (el && (busy || messages.length)) el.scrollTo({ top: el.scrollHeight, behavior: 'smooth' });
  }, [messages.length, busy]);

  const transcript = useMemo(() => transcriptForAI(video.cues), [video.cues]);
  const isLong = estimateTokens(transcript) > MAX_CONTEXT_TOKENS;

  const context = async (signal: AbortSignal): Promise<string> => {
    if (!isLong) return transcript;
    const cacheKey = `${video.id}:${video.language}`;
    const cached = reducedCache.get(cacheKey);
    if (cached) return cached;
    // Summarize by parts, then answer from the notes.
    const parts = chunkText(transcript, MAX_CONTEXT_TOKENS * 3);
    const notes: string[] = [];
    for (let i = 0; i < parts.length; i++) {
      setProgress(t('ai.partProgress', { n: i + 1, total: parts.length }));
      const sys = buildSystemPrompt(
        {
          title: video.title,
          author: video.author,
          url: video.url,
          captionLanguage: video.language,
          autoGenerated: video.autoGenerated,
          transcript: parts[i]!,
        },
        answerLang
      );
      const note = await withModelFallback(provider, apiKey, model, (m) =>
        streamChat({
          provider,
          apiKey,
          model: m,
          system: sys,
          messages: [
            {
              role: 'user',
              content:
                'Write detailed notes of this part of the video, keeping every important fact, number and name, with timestamps like [12:34].',
            },
          ],
          signal,
          onDelta: () => undefined,
        })
      );
      notes.push(note);
    }
    setProgress(null);
    const reduced = notes.join('\n\n');
    reducedCache.set(cacheKey, reduced);
    return reduced;
  };

  const run = async (history: StoredMessage[], before: StoredMessage[] = messages) => {
    touched.current = true;
    setError(null);
    setMessages(history);
    setStreaming('');
    const ctrl = new AbortController();
    abort.current = ctrl;
    try {
      const ctx = await context(ctrl.signal);
      const system = buildSystemPrompt(
        {
          title: video.title,
          author: video.author,
          url: video.url,
          captionLanguage: languageLabel(video.language, 'en'),
          autoGenerated: video.autoGenerated,
          transcript: ctx,
        },
        answerLang
      );
      const apiMessages: ChatMessage[] = history.map((m) => ({ role: m.role, content: m.content }));
      const used = { model };
      const answer = await withModelFallback(provider, apiKey, model, (m) => {
        used.model = m;
        return streamChat({
          provider,
          apiKey,
          model: m,
          system,
          messages: apiMessages,
          signal: ctrl.signal,
          onDelta: (text) => setStreaming(text),
        });
      });
      const next: StoredMessage[] = [
        ...history,
        { role: 'assistant', content: answer || '…', provider, model: used.model, at: Date.now() },
      ];
      setMessages(next);
      if (getSettings().saveHistory) void saveChat(video.id, next);
    } catch (e) {
      if (e instanceof AiError && e.code === 'aborted') {
        // Stopped: put the conversation back exactly as it was.
        setMessages(before);
      } else {
        const text = aiErrorMessage(t, provider, e);
        if (e instanceof AiError && e.code === 'invalid_key') {
          // The key stopped working (revoked, typo…): ask for a new one.
          toast(text, 'error');
          setMessages(history.slice(0, -1));
          setKey(provider, null);
        } else {
          setError({ text, retry: history });
        }
      }
    } finally {
      setStreaming(null);
      setProgress(null);
      abort.current = null;
    }
  };

  const ask = (content: string, preset?: PresetId): boolean => {
    if (busy || !content.trim()) return false;
    void run([...messages, { role: 'user', content: content.trim(), preset, at: Date.now() }]);
    return true;
  };

  const runPreset = (id: PresetId) => void ask(PRESET_PROMPTS[id], id);

  useEffect(() => {
    const onPreset = (e: Event) => runPreset((e as CustomEvent<PresetId>).detail);
    window.addEventListener(PRESET_EVENT, onPreset);
    return () => window.removeEventListener(PRESET_EVENT, onPreset);
  });

  const submit = (e: FormEvent) => {
    e.preventDefault();
    if (ask(draft)) setDraft('');
  };

  const clear = () => {
    setMessages([]);
    setError(null);
    void saveChat(video.id, []);
  };

  const exportChat = () => {
    const lines = messages.map((m) =>
      m.role === 'user' ? `## ${m.preset ? t(`ai.presets.${m.preset}`) : m.content}\n` : `${m.content}\n`
    );
    downloadFile(
      `${video.title || 'bitsub'} - IA.md`.replace(/[\\/:*?"<>|]/g, ''),
      `# ${video.title}\n${video.url}\n\n${lines.join('\n')}`,
      'text/markdown'
    );
  };

  const lastAnswer = [...messages].reverse().find((m) => m.role === 'assistant');

  return (
    <div className="flex min-h-0 flex-1 flex-col gap-4">
      <div>
        <p className="mb-2 text-sm font-semibold">{t('ai.presetsTitle')}</p>
        <div className="flex flex-wrap gap-2">
          {PRESETS.map((id) => (
            <button
              key={id}
              type="button"
              disabled={busy}
              onClick={() => runPreset(id)}
              className={cn(
                'border-2 border-line px-3 py-1.5 text-[0.95rem] font-semibold transition-colors disabled:opacity-50',
                id === 'summary' ? 'bg-primary text-on-primary hover:bg-primary-hover' : 'bg-surface hover:bg-surface-alt'
              )}
            >
              {t(`ai.presets.${id}`)}
            </button>
          ))}
        </div>
      </div>

      {isLong && !messages.length ? <Callout icon="clock">{t('ai.longVideo')}</Callout> : null}

      <div ref={scroller} className="scroll-thin -mx-1 min-h-0 flex-1 space-y-4 overflow-y-auto px-1" aria-live="polite">
        {!messages.length && !busy ? (
          <div className="flex items-center gap-4 border-2 border-dashed border-hair p-4">
            <Mascot size={48} />
            <div className="space-y-2">
              <p className="text-sm font-semibold text-muted">{t('ai.suggestions')}</p>
              <div className="flex flex-wrap gap-2">
                {(['suggestion1', 'suggestion2', 'suggestion3'] as const).map((k) => (
                  <button key={k} type="button" onClick={() => ask(t(`ai.${k}`))} className="link text-left text-[0.95rem]">
                    {t(`ai.${k}`)}
                  </button>
                ))}
              </div>
            </div>
          </div>
        ) : null}

        {messages.map((m, i) =>
          m.role === 'user' ? (
            <div key={i} className="flex justify-end">
              <p className="max-w-[88%] border-2 border-line bg-surface-alt px-3 py-2 font-medium">
                {m.preset ? (
                  <span className="flex items-center gap-2">
                    <Icon name="sparkle" size={16} />
                    {t(`ai.presets.${m.preset}`)}
                  </span>
                ) : (
                  m.content
                )}
              </p>
            </div>
          ) : (
            <article key={i} className="group">
              <Markdown text={m.content} />
              <div className="mt-2 flex flex-wrap items-center gap-1 text-sm text-muted">
                <button
                  type="button"
                  className="inline-flex items-center gap-1.5 px-1.5 py-1 hover:bg-surface-alt hover:text-text"
                  onClick={() =>
                    void copyText(m.content).then((ok) =>
                      toast(ok ? t('toast.answerCopied') : t('toast.copyFailed'), ok ? 'success' : 'error')
                    )
                  }
                >
                  <Icon name="copy" size={15} />
                  {t('ai.copyAnswer')}
                </button>
                {m === lastAnswer && !busy ? (
                  <button
                    type="button"
                    className="inline-flex items-center gap-1.5 px-1.5 py-1 hover:bg-surface-alt hover:text-text"
                    onClick={() => void run(messages.slice(0, i))}
                  >
                    <Icon name="refresh" size={15} />
                    {t('ai.regenerate')}
                  </button>
                ) : null}
              </div>
            </article>
          )
        )}

        {busy ? (
          <article>
            {streaming ? (
              <Markdown text={streaming} />
            ) : (
              <div className="flex items-center gap-4 border-2 border-line bg-surface-alt p-3">
                <ThinkingMascot size={96} />
                <div className="min-w-0 space-y-1.5" aria-live="polite">
                  <p className="font-semibold">{slow ? t('ai.slowTitle') : (progress ?? t('ai.thinking'))}</p>
                  {slow ? (
                    <>
                      <p className="text-sm leading-snug text-muted">{t('ai.slowText', { provider: provider === 'gemini' ? 'Gemini' : 'ChatGPT' })}</p>
                      <button type="button" className="link text-sm font-semibold" onClick={() => abort.current?.abort()}>
                        {t('ai.slowStop')}
                      </button>
                    </>
                  ) : null}
                </div>
              </div>
            )}
          </article>
        ) : null}

        {error ? (
          <Callout
            tone="error"
            action={
              <Button size="sm" icon="refresh" onClick={() => void run(error.retry)}>
                {t('common.retry')}
              </Button>
            }
          >
            {error.text}
          </Callout>
        ) : null}
      </div>

      <form onSubmit={submit} className="flex items-end gap-2">
        <label className="sr-only" htmlFor="ai-ask">
          {t('ai.askPlaceholder')}
        </label>
        <textarea
          id="ai-ask"
          rows={1}
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) {
              e.preventDefault();
              if (ask(draft)) setDraft('');
            }
          }}
          placeholder={t('ai.askPlaceholder')}
          className="field max-h-40 min-h-[52px] flex-1 [field-sizing:content]"
        />
        {busy ? (
          <Button
            onClick={() => abort.current?.abort()}
            className="btn-icon min-h-[52px] min-w-[52px]"
            aria-label={t('common.stop')}
          >
            <Icon name="stop" />
          </Button>
        ) : (
          <Button
            type="submit"
            variant="primary"
            disabled={!draft.trim()}
            className="btn-icon min-h-[52px] min-w-[52px]"
            aria-label={t('ai.send')}
          >
            <Icon name="send" />
          </Button>
        )}
      </form>

      <div className="flex flex-wrap items-center justify-between gap-x-4 gap-y-1 text-sm text-muted">
        <span>
          {t('ai.using', { provider: provider === 'gemini' ? 'Gemini' : 'ChatGPT', model })} ·{' '}
          <Link href="/settings#ai" className="link font-semibold text-text">
            {t('ai.change')}
          </Link>
        </span>
        {messages.length ? (
          <span className="flex gap-3">
            <button type="button" className="link" onClick={exportChat}>
              {t('ai.downloadChat')}
            </button>
            <button type="button" className="link" onClick={clear} disabled={busy}>
              {t('ai.clearChat')}
            </button>
          </span>
        ) : null}
      </div>
    </div>
  );
}
