import { useEffect, useId, useState, type FormEvent } from 'react';
import { useTranslation } from 'react-i18next';
import { parsePastedTranscript } from '@/lib/transcript';
import { saveVideo } from '@/lib/db';
import { navigate } from '@/lib/router';
import { Button, Modal } from './ui';

export function PasteModal({
  open,
  onClose,
  defaultTitle = '',
  videoId = null,
}: {
  open: boolean;
  onClose: () => void;
  defaultTitle?: string;
  videoId?: string | null;
}) {
  const { t } = useTranslation();
  const [title, setTitle] = useState(defaultTitle);
  const [text, setText] = useState('');
  const [error, setError] = useState<string | null>(null);
  const titleId = useId();
  const textId = useId();
  const steps = t('paste.how', { returnObjects: true }) as unknown as string[];

  useEffect(() => {
    if (open) setTitle(defaultTitle);
  }, [open, defaultTitle]);

  const submit = async (e: FormEvent) => {
    e.preventDefault();
    const cues = parsePastedTranscript(text);
    const words = cues.reduce((n, c) => n + c.text.split(/\s+/).length, 0);
    if (words < 8) {
      setError(t('paste.tooShort'));
      return;
    }
    const id = `paste-${Date.now().toString(36)}`;
    await saveVideo({
      id,
      videoId,
      title: title.trim() || t('paste.pastedTitle'),
      author: '',
      lengthSeconds: Math.ceil(cues[cues.length - 1]?.end ?? 0),
      language: document.documentElement.lang || 'pt-BR',
      autoGenerated: false,
      translated: false,
      pasted: true,
      cues,
      requested: 'original',
      openedAt: Date.now(),
    });
    setText('');
    onClose();
    navigate(`/text/${id}`);
  };

  return (
    <Modal open={open} onClose={onClose} title={t('paste.title')} wide>
      <p className="-mt-1 mb-5 leading-relaxed text-muted">{t('paste.intro')}</p>
      <details className="mb-5 border-2 border-line bg-surface-alt">
        <summary className="cursor-pointer px-4 py-3 font-semibold">{t('paste.howTitle')}</summary>
        <ol className="list-decimal space-y-1.5 px-4 pb-4 pl-9">
          {steps.map((s, i) => (
            <li key={i}>{s}</li>
          ))}
        </ol>
      </details>
      <form onSubmit={(e) => void submit(e)} className="space-y-4">
        <div>
          <label htmlFor={titleId} className="mb-1.5 block text-sm font-semibold">
            {t('paste.titleLabel')}
          </label>
          <input
            id={titleId}
            className="field"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder={t('paste.titlePlaceholder')}
          />
        </div>
        <div>
          <label htmlFor={textId} className="mb-1.5 block text-sm font-semibold">
            {t('paste.textLabel')}
          </label>
          <textarea
            id={textId}
            className="field min-h-56 font-mono text-[0.9rem]"
            value={text}
            onChange={(e) => {
              setText(e.target.value);
              setError(null);
            }}
            placeholder={t('paste.textPlaceholder')}
          />
          {error ? (
            <p role="alert" className="mt-2 font-medium text-error">
              {error}
            </p>
          ) : null}
        </div>
        <Button type="submit" variant="primary" className="w-full" disabled={!text.trim()} iconRight="arrowRight">
          {t('paste.submit')}
        </Button>
      </form>
    </Modal>
  );
}
