import { useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import type { LoadedVideo, Notice } from '@/hooks/useVideo';
import { onSeekRequest, registerFrame } from '@/lib/player';
import { formatClock, wordCount } from '@/lib/transcript';
import { thumbnailUrl, watchUrl } from '@/lib/youtube/url';
import { languageLabel } from '@/lib/languages';
import { currentLanguage } from '@/i18n';
import { Icon } from './Icon';
import { LanguagePicker } from './LanguagePicker';
import { Mascot } from './Mascot';
import { Callout, Tag } from './ui';

function Player({ videoId, title, start }: { videoId: string; title: string; start?: number }) {
  const { t } = useTranslation();
  const [playing, setPlaying] = useState<{ at: number } | null>(null);

  const box = useRef<HTMLDivElement>(null);
  useEffect(
    () =>
      onSeekRequest((s) => {
        // Show the video only when it opens; later jumps keep the reader where they are.
        const opening = !box.current?.querySelector('iframe');
        setPlaying((p) => p ?? { at: s });
        const r = box.current?.getBoundingClientRect();
        if (opening && r && (r.bottom < 80 || r.top > window.innerHeight))
          box.current?.scrollIntoView({ behavior: 'smooth', block: 'center' });
      }),
    []
  );
  useEffect(() => () => registerFrame(null), []);
  useEffect(() => setPlaying(null), [videoId]);

  if (playing) {
    const params = new URLSearchParams({
      autoplay: '1',
      enablejsapi: '1',
      rel: '0',
      modestbranding: '1',
      playsinline: '1',
      origin: window.location.origin,
      start: String(Math.floor(playing.at)),
      hl: currentLanguage(),
    });
    return (
      <div ref={box} className="absolute inset-0">
        <iframe
          ref={registerFrame}
          className="absolute inset-0 h-full w-full"
          src={`https://www.youtube-nocookie.com/embed/${videoId}?${params.toString()}`}
          title={title}
          allow="autoplay; encrypted-media; picture-in-picture; fullscreen"
          allowFullScreen
        />
      </div>
    );
  }
  return (
    <div ref={box} className="absolute inset-0">
      <button
        type="button"
        className="group absolute inset-0 h-full w-full"
        onClick={() => setPlaying({ at: start ?? 0 })}
        aria-label={`${t('video.play')}: ${title}`}
      >
        <img src={thumbnailUrl(videoId, 'hq')} alt="" className="h-full w-full object-cover" loading="eager" decoding="async" />
        <span className="absolute inset-0 bg-[rgb(13_43_69/0.15)] transition-colors group-hover:bg-[rgb(13_43_69/0.3)]" />
        <span className="absolute left-1/2 top-1/2 flex -translate-x-1/2 -translate-y-1/2 items-center gap-2 border-2 border-line bg-primary px-4 py-2.5 font-semibold text-on-primary shadow-hard transition-transform group-hover:-translate-y-[calc(50%+2px)]">
          <Icon name="play" size={18} />
          {t('video.play')}
        </span>
      </button>
    </div>
  );
}

export function VideoHeader({
  video,
  notice,
  requested,
  onLanguage,
  start,
}: {
  video: LoadedVideo;
  notice: Notice;
  requested: string;
  onLanguage?: (lang: string) => void;
  start?: number;
}) {
  const { t } = useTranslation();
  const ui = currentLanguage();
  const lastEnd = video.cues[video.cues.length - 1]?.end ?? 0;
  const duration = formatClock(video.lengthSeconds || lastEnd);
  const langName = languageLabel(video.language, ui);
  const requestedName = requested === 'original' ? '' : languageLabel(requested, ui);

  return (
    <section className="grid gap-5 md:grid-cols-12 md:gap-8" aria-labelledby="video-title">
      <div className="md:col-span-5">
        <div className="card relative aspect-video overflow-hidden bg-ink">
          {video.videoId ? (
            <Player videoId={video.videoId} title={video.title} start={start} />
          ) : (
            <div className="flex h-full items-center justify-center">
              <Mascot size={96} mood="happy" />
            </div>
          )}
        </div>
      </div>
      <div className="flex min-w-0 flex-col gap-4 md:col-span-7">
        <div className="flex flex-wrap gap-2">
          <Tag tone="ink">
            <Icon name="globe" size={12} strokeWidth={3} />
            {langName}
          </Tag>
          <Tag>
            {video.pasted
              ? t('video.pasted')
              : video.translated
                ? t('video.translated')
                : video.autoGenerated
                  ? t('video.auto')
                  : t('video.manual')}
          </Tag>
        </div>
        <h1
          id="video-title"
          className="text-balance text-[1.75rem] font-semibold leading-[1.1] tracking-[-0.02em] sm:text-[2.125rem]"
        >
          {video.title || '—'}
        </h1>
        <p className="text-muted">
          {video.author ? <span className="font-semibold text-text">{video.author}</span> : null}
          {video.author ? ' · ' : null}
          <span className="tnum">{t('video.stats', { duration, words: wordCount(video.cues).toLocaleString(ui) })}</span>
        </p>
        <div className="flex flex-wrap items-end gap-3">
          {onLanguage && !video.pasted ? (
            <LanguagePicker
              className="w-full xs:w-64"
              value={requested}
              onChange={onLanguage}
              label={t('video.changeLanguage')}
            />
          ) : null}
          {video.videoId ? (
            <a className="btn" href={watchUrl(video.videoId)} target="_blank" rel="noopener noreferrer">
              <Icon name="external" size={18} />
              {t('video.watchOnYouTube')}
            </a>
          ) : null}
        </div>
        {notice ? (
          <Callout icon="info">
            {notice === 'translateFailed'
              ? t('video.translateFailed', { lang: requestedName })
              : t('video.notInLanguage', { lang: requestedName })}
          </Callout>
        ) : null}
      </div>
    </section>
  );
}
